// <auto-generated />
namespace Manager.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StartDataBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartDataBase));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111937293_StartDataBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
